[package]
name = "israt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

imgui = {version = "0.8.2",features = ["tables-api"]}
imgui-glium-renderer = "0.8.2"
glium = { version = "0.30.2", default-features = true }
imgui-winit-support = "0.8.2"
winit = "0.25.0"
clipboard = "0.5"
tectonic = "0.9.0"
chrono = "0.4.19"
